Pass functions UI
aditiii23/virtualPermissions pull request #21
Opened 2023-04-04 08:14 UTC by aditiii23

2023-04-05 07:58 UTC, mrpriyansh requested changes

2023-04-05 07:58 UTC, mrpriyansh commented on frontend/src/components/GeneratePass/GeneratePass.js
> +          localStorage.setItem("newPass", JSON.stringify(res.data.newPass))
What do you want to do with this line?

2023-04-05 07:58 UTC, mrpriyansh commented on frontend/src/components/Signup/Signup.js
> +  const [isLoading, setIsLoading] = useState(false)
Why these changes are visible here??

2023-04-05 07:58 UTC, mrpriyansh commented on frontend/src/components/ViewPasses/ViewPasses.js
> +              key={item?.id}
Do you know why key is used?

2023-04-05 08:16 UTC, aditiii23 commented on frontend/src/components/ViewPasses/ViewPasses.js
> +              key={item?.id}
Key is used basically to give an identity to the elements. Like here, each pass id is the key for each pass. This is for unique identification for each pass.

2023-04-05 08:17 UTC, aditiii23 commented on frontend/src/components/Signup/Signup.js
> +  const [isLoading, setIsLoading] = useState(false)
Will figure out and tell you..

2023-04-05 08:19 UTC, aditiii23 commented on frontend/src/components/GeneratePass/GeneratePass.js
> +          localStorage.setItem("newPass", JSON.stringify(res.data.newPass))
Store the new pass data in the string form in the local storage.

2023-04-06 09:10 UTC, mrpriyansh requested changes

2023-04-06 09:10 UTC, mrpriyansh commented on frontend/src/components/GeneratePass/GeneratePass.js
> +          localStorage.setItem("newPass", JSON.stringify(res.data.newPass))
Are you using the stored pass anywhere?

2023-04-06 14:07 UTC, aditiii23 commented on frontend/src/components/GeneratePass/GeneratePass.js
> +          localStorage.setItem("newPass", JSON.stringify(res.data.newPass))
No...

2023-04-11 13:03 UTC, mrpriyansh approved these changes

2023-04-11 13:03 UTC, merged